[build-system]
requires = ["maturin>=0.13,<0.14"]
build-backend = "maturin"

[project]
name = "my_project"
version = "0.1.0"
authors = ["Your Name <you@example.com>"]
description = "A Python project that uses Rust."
readme = "README.md"
license = { text = "MIT" }

[tool.maturin]
bindings = "pyo3"
