name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install maturin
      run: pip install maturin==1.7.8

    - name: Build Python package
      run: maturin build --target x86_64-unknown-linux-gnu --release

    - name: Build Python package
      run: maturin build --target aarch64-unknown-linux-gnu --release

    - name: Build and publish
      env:
        MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: maturin publish --non-interactive
