name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install maturin
      run: pip install maturin==1.7.8

    - name: Debug Environment Variables
      run: |
        echo "PYPI_USERNAME: $PYPI_USERNAME"

    - name: Build Python package
      run: maturin build --release

    - name: Upload to PyPI
      env:
        PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: maturin publish
