name: Build and Release with Custom Docker Container

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    container:
      image: ghcr.io/okamumu/maturin:1.7.8

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build for x86_64
      run: |
        mkdir -p dist
        maturin build --release --target x86_64-unknown-linux-gnu -i python3.9 -i python3.10 -i python3.11 --zig --out dist

    - name: Build for ARM (aarch64)
      run: |
        maturin build --release --target aarch64-unknown-linux-gnu -i python3.9 -i python3.10 -i python3.11 --zig --out dist

    - name: Build source distribution
      run: |
        maturin sdist --out dist

    - name: Show dist folder contents
      run: |
        echo "Contents of dist folder:"
        ls -lh dist

    - name: Upload dist folder as artifact
      uses: actions/upload-artifact@v3
      with:
        name: dist-folder
        path: dist/

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: "__token__"
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        PYTHON_KEYRING_BACKEND: "keyring.backends.null.Keyring"
      run: |
        twine upload dist/*.whl dist/*.tar.gz
